/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import atm.Account;
import static atm.Account.Loginacount;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class ATMSystem extends javax.swing.JFrame {

    static JPanel pnMain, childPanel;
    static int account;

    public void view() {
        pnMain = new JPanel();
        this.add(pnMain, BorderLayout.CENTER);
        this.setSize(750, 425);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(ATMSystem.EXIT_ON_CLOSE);
    }
//    

    public ATMSystem() {
        initComponents();
        Clock c = new Clock();
        Thread t = new Thread(c);
        t.start();
        pnMenu.add(c, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JMenuBar();
        mnDangNhap = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mnTaiKhoan = new javax.swing.JMenu();
        mnDoiMatKhau = new javax.swing.JMenuItem();
        mnThongTinTK = new javax.swing.JMenuItem();
        mnHeThong = new javax.swing.JMenu();
        mnRutTien = new javax.swing.JMenuItem();
        mnGuiTien = new javax.swing.JMenuItem();
        mnChuyenTien = new javax.swing.JMenuItem();
        mnNhatKyGiaoDich = new javax.swing.JMenuItem();
        mnDangXuat = new javax.swing.JMenu();
        mnThoat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        mnDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        mnDangNhap.setText("Đăng nhập");
        mnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnDangNhapMouseClicked(evt);
            }
        });
        mnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDangNhapActionPerformed(evt);
            }
        });
        pnMenu.add(mnDangNhap);

        jMenu2.setText("Đăng ký tài khoản");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        pnMenu.add(jMenu2);

        mnTaiKhoan.setText("Tài khoản");

        mnDoiMatKhau.setText("Đổi mật khẩu");
        mnDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnDoiMatKhauMouseReleased(evt);
            }
        });
        mnTaiKhoan.add(mnDoiMatKhau);

        mnThongTinTK.setText("Xem thông tin");
        mnThongTinTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnThongTinTKMouseReleased(evt);
            }
        });
        mnTaiKhoan.add(mnThongTinTK);

        pnMenu.add(mnTaiKhoan);

        mnHeThong.setBackground(new java.awt.Color(255, 255, 255));
        mnHeThong.setText("Hệ thống");
        mnHeThong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnHeThongMouseReleased(evt);
            }
        });

        mnRutTien.setText("Rút tiền");
        mnRutTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnRutTienMouseReleased(evt);
            }
        });
        mnHeThong.add(mnRutTien);

        mnGuiTien.setBackground(new java.awt.Color(255, 255, 255));
        mnGuiTien.setText("Gửi tiền");
        mnGuiTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnGuiTienMouseReleased(evt);
            }
        });
        mnHeThong.add(mnGuiTien);

        mnChuyenTien.setText("Chuyển tiền");
        mnChuyenTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnChuyenTienMouseReleased(evt);
            }
        });
        mnHeThong.add(mnChuyenTien);

        mnNhatKyGiaoDich.setText("Nhật ký giao dịch");
        mnNhatKyGiaoDich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnNhatKyGiaoDichMouseReleased(evt);
            }
        });
        mnHeThong.add(mnNhatKyGiaoDich);

        pnMenu.add(mnHeThong);

        mnDangXuat.setText("Đăng xuất");
        mnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnDangXuatMouseClicked(evt);
            }
        });
        pnMenu.add(mnDangXuat);

        mnThoat.setBackground(new java.awt.Color(255, 255, 255));
        mnThoat.setText("Thoát");
        mnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnThoatMouseClicked(evt);
            }
        });
        mnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnThoatActionPerformed(evt);
            }
        });
        pnMenu.add(mnThoat);

        setJMenuBar(pnMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void mnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnThoatActionPerformed
    }//GEN-LAST:event_mnThoatActionPerformed

    private void mnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDangNhapActionPerformed

    }//GEN-LAST:event_mnDangNhapActionPerformed

    private void mnDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDangNhapMouseClicked
        if (account != 0) {
            JOptionPane.showMessageDialog(null, "Bạn đã đăng nhập");
        } else {
            showPanel(new Login());
        }
    }//GEN-LAST:event_mnDangNhapMouseClicked

    private void mnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnThoatMouseClicked
        int n = JOptionPane.showConfirmDialog(null, "Bạn có chắc bạn muốn thoát khỏi?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_mnThoatMouseClicked

    private void mnGuiTienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnGuiTienMouseReleased
        if (account == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng đăng nhập", "Thông báo", 1);
        } else {
            showPanel(new GuiTien());
        }
    }//GEN-LAST:event_mnGuiTienMouseReleased

    private void mnHeThongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnHeThongMouseReleased

    }//GEN-LAST:event_mnHeThongMouseReleased

    private void mnNhatKyGiaoDichMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnNhatKyGiaoDichMouseReleased
        if (account == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng đăng nhập", "Thông báo", 1);
        } else {
            showPanel(new NhatKyGD());
        }
    }//GEN-LAST:event_mnNhatKyGiaoDichMouseReleased

    private void mnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDangXuatMouseClicked
        if (account == 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa đăng nhập");
        } else {
            int n = JOptionPane.showConfirmDialog(null, "Bạn có chắc bạn muốn đăng xuất ?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION) {
                account = 0;
                JOptionPane.showMessageDialog(null, "Bạn đã đăng xuất", "Thông báo", 1);
                showPanel(new Wellcom());
            }
        }
    }//GEN-LAST:event_mnDangXuatMouseClicked

    private void mnRutTienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnRutTienMouseReleased
        if (account == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng đăng nhập", "Thông báo", 1);
        } else {
            showPanel(new RutTien());
        }
    }//GEN-LAST:event_mnRutTienMouseReleased

    private void mnDoiMatKhauMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDoiMatKhauMouseReleased
        if (account == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng đăng nhập", "Thông báo", 1);
        } else {
            showPanel(new DoiMatKhau());
        }
    }//GEN-LAST:event_mnDoiMatKhauMouseReleased

    private void mnThongTinTKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnThongTinTKMouseReleased
        if (account == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng đăng nhập", "Thông báo", 1);
        } else {
            showPanel(new ThongTinTK());
        }
    }//GEN-LAST:event_mnThongTinTKMouseReleased

    private void mnChuyenTienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnChuyenTienMouseReleased
        if (account == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng đăng nhập", "Thông báo", 1);
        } else {
            showPanel(new ChuyenTien());
        }
    }//GEN-LAST:event_mnChuyenTienMouseReleased

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        showPanel(new DangKyTaiKhoan());
    }//GEN-LAST:event_jMenu2MouseClicked
    static void showPanel(JPanel panel) {
        childPanel = panel;
        pnMain.removeAll();
        pnMain.add(childPanel);
        pnMain.validate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ATMSystem atm = new ATMSystem();
                atm.setSize(750, 400);
                atm.setLocationRelativeTo(null);
                atm.setVisible(true);
                atm.view();
                showPanel(new Wellcom());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem mnChuyenTien;
    private javax.swing.JMenu mnDangNhap;
    private javax.swing.JMenu mnDangXuat;
    private javax.swing.JMenuItem mnDoiMatKhau;
    private javax.swing.JMenuItem mnGuiTien;
    private javax.swing.JMenu mnHeThong;
    private javax.swing.JMenuItem mnNhatKyGiaoDich;
    private javax.swing.JMenuItem mnRutTien;
    private javax.swing.JMenu mnTaiKhoan;
    private javax.swing.JMenu mnThoat;
    private javax.swing.JMenuItem mnThongTinTK;
    private javax.swing.JMenuBar pnMenu;
    // End of variables declaration//GEN-END:variables

}
