/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.sql.SQLException;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class ChuyenTien extends javax.swing.JPanel {

    /**
     * Creates new form ChuyenTien
     */
    public ChuyenTien() {
        initComponents();
        TaiKhoan();
        String code= String.valueOf(random());
        txtRdcode.setText(code);
        txtRdcode.setEditable(false);
        try {
            Vector<Account> vt = Account.getAccount();
            DefaultComboBoxModel dcb = new DefaultComboBoxModel(vt);
            cbMatkNhan.setModel(dcb);
        } catch (SQLException ex) {
            Logger.getLogger(ChuyenTien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMaTKChuyen = new javax.swing.JTextField();
        txtSotienchuyen = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        txtRdcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnRefesh = new javax.swing.JButton();
        cbMatkNhan = new javax.swing.JComboBox<>();
        txtSodu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Chuyển tiền");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Mã TK chuyển tiền");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mã TK nhận tiền");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Số tiền chuyển");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Mã xác nhận");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Chuyển tiền");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnRefesh.setIcon(new javax.swing.ImageIcon("D:\\Source Code for Java\\ATM\\1.png")); // NOI18N
        btnRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Số tiền còn trong TK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtRdcode, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbMatkNhan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaTKChuyen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSodu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSotienchuyen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThoat)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefesh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaTKChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMatkNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSotienchuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRdcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCode)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefesh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(jButton1))
                .addGap(95, 95, 95))
        );
    }// </editor-fold>//GEN-END:initComponents

    private int ktrAmount(String ktr){
        int kq=0;
        try 
        { 
            String regex = "^\\d+$"; 
            if(ktr.matches(regex)) 
            { 
                kq=1;
            } 
        } 
        catch(Exception ex) 
        { 
            throw ex; 
        } 
        return kq;
    }
    private boolean ktrMaxacnhan(){
        int code = Integer.parseInt(txtCode.getText());
        int code1=Integer.parseInt(txtRdcode.getText());
        if(code == code1){
                return true;
            }
            return false;
    } 
    private void TaiKhoan(){
        int accode = ATMSystem.account;
        try {
            Account acc = new Account(accode);
            txtMaTKChuyen.setText(String.valueOf(acc.getAccountid()));
            txtSodu.setText(String.valueOf(acc.getBalance()));
        } catch (SQLException ex) {
            Logger.getLogger(ChuyenTien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private int MaTKNhan(){
        int mtk=0;
        String tk=cbMatkNhan.getSelectedItem().toString().substring(1,5);
        mtk=Integer.parseInt(tk);
        if(mtk == ATMSystem.account){
            mtk=0;
        }
        return mtk; 
    }
    private double sotienchuyen(){
        double tien,tienchuyen;
        String sotien=txtSotienchuyen.getText();
        if(ktrAmount(sotien)!=0){
            tienchuyen=Double.parseDouble(sotien);
            tien=Double.parseDouble(txtSodu.getText());
            if(tienchuyen >= tien || tienchuyen <10 ){
                tienchuyen = 0;
            }
            else tienchuyen=Double.parseDouble(sotien);
        }
        else tienchuyen=0;
        return tienchuyen;
    }
    private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshActionPerformed
        String code= String.valueOf(random());
        txtRdcode.setText(code);
    }//GEN-LAST:event_btnRefeshActionPerformed
    
    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int n = JOptionPane.showConfirmDialog(null,"Bạn có chắc bạn muốn thoát khỏi?", "Thông báo",JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION)
            ATMSystem.showPanel(new Wellcom());
    }//GEN-LAST:event_btnThoatActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(MaTKNhan()==0){
          JOptionPane.showMessageDialog(null,"Tài khoản không hợp lệ");
      }
      else {
        if(sotienchuyen()==0){
             JOptionPane.showMessageDialog(null,"Số tiền không hợp lệ", "Thông báo",1);
             txtSotienchuyen.setText("");
         }
         else{
             if(ktrMaxacnhan()==false) {
                JOptionPane.showMessageDialog(null,"Mã xác nhận chưa đúng", "Thông báo",1);
                String code= String.valueOf(random());
                txtRdcode.setText(code);
                txtCode.setText("");
             }
             else{
                int tkchuyen,tknhan;
                double tienchuyen;
                tkchuyen=Integer.parseInt(txtMaTKChuyen.getText());
                tknhan=MaTKNhan();
                    tienchuyen=sotienchuyen();
                    Deal dl = new Deal();
                    try {
                        dl.ChuyenTien(tkchuyen, tknhan, tienchuyen);
                        if(dl!=null){
                             JOptionPane.showMessageDialog(null,"Đã chuyển tiền thành công", "Thông báo",1);
                             txtSotienchuyen.setText("");
                             txtCode.setText("");
                             int n = JOptionPane.showConfirmDialog(null,"Tiếp tục thực hiện các giao dịch ?", "Cảnh báo",JOptionPane.YES_NO_OPTION);
                             if(n == JOptionPane.YES_OPTION)
                                   ATMSystem.showPanel(new Wellcom());
                             else if(n==JOptionPane.NO_OPTION){
                                       ATMSystem.account=0;
                                       JOptionPane.showMessageDialog(null, "Bạn đã đăng xuất");
                                       ATMSystem.showPanel(new Login());   
                                   }
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(ChuyenTien.class.getName()).log(Level.SEVERE, null, ex);
                    }
             } 
         }
      }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private int rand(int min,int max){
        try {
                Random rn = new Random();
                int range = max - min + 1;
                int randomNum = min + rn.nextInt(range);
                return randomNum;
            } catch (Exception e) {
                e.printStackTrace();
                return -1;
            }
     }
    private int random(){
          int rand = rand(1000,9000);
          return rand;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefesh;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbMatkNhan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtMaTKChuyen;
    private javax.swing.JTextField txtRdcode;
    private javax.swing.JTextField txtSodu;
    private javax.swing.JTextField txtSotienchuyen;
    // End of variables declaration//GEN-END:variables
}
