/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class GuiTien extends javax.swing.JPanel {

    /**
     * Creates new form GuiTien
     */
    public GuiTien() {
        initComponents();
        String code= String.valueOf(random());
        txtRdcode.setText(code);
        txtRdcode.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSotien = new javax.swing.JTextField();
        btnGui = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtCode = new javax.swing.JTextField();
        txtRdcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnGui.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGui.setForeground(new java.awt.Color(0, 0, 153));
        btnGui.setText("Gửi tiền");
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(204, 0, 0));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Số tiền gửi");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mã xác nhận");

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon("D:\\Source Code for Java\\ATM\\1.png")); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Gửi tiền vào tài khoản");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtSotien, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRdcode, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGui)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThoat)))
                .addContainerGap(432, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSotien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtRdcode)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGui)
                    .addComponent(btnThoat))
                .addGap(92, 92, 92))
        );
    }// </editor-fold>//GEN-END:initComponents
     private int ktrAmount(String ktr){
        int kq=0;
        try 
        { 
            String regex = "^\\d+$"; 
            if(ktr.matches(regex)) 
            { 
                kq=1;
            } 
        } 
        catch(Exception ex) 
        { 
            throw ex; 
        } 
        return kq;
    }
    private boolean ktrMaxacnhan(){
        int code = Integer.parseInt(txtCode.getText());
        int code1=Integer.parseInt(txtRdcode.getText());
        if(code == code1){
                return true;
            }
            return false;
    } 
    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
        Date today = new Date(System.currentTimeMillis());
        SimpleDateFormat timeFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss ");
        String time = timeFormat.format(today.getTime());
        String ktr=txtSotien.getText();
        if(ktrAmount(ktr)==0 || ktr==null){
                JOptionPane.showMessageDialog(null,"Số tiền không hợp lệ", "Thông báo",1);
        }
        else {
            double amount=Double.parseDouble(ktr);     
            Deal dl=new Deal();
            if(ktrMaxacnhan()==true){       
                try {
                    dl.SendAmount(ATMSystem.account, "Gửi tiền", "Thành công", amount);
                    if(dl!=null){
                        JOptionPane.showMessageDialog(null,"Đã gửi tiền thành công vào lúc "+time, "Thông báo",1);
                        txtSotien.setText("");
                        txtCode.setText("");
                        int n = JOptionPane.showConfirmDialog(null,"Tiếp tục thực hiện các giao dịch ?", "Cảnh báo",JOptionPane.YES_NO_OPTION);
                        if(n == JOptionPane.YES_OPTION)
                               ATMSystem.showPanel(new Wellcom());
                        else if(n==JOptionPane.NO_OPTION){
                                   ATMSystem.account=0;
                                   JOptionPane.showMessageDialog(null, "Bạn đã đăng xuất");
                                   ATMSystem.showPanel(new Login());   
                               }
                    }
                    else JOptionPane.showMessageDialog(null,"Nạp tiền không thành công", "Thông báo",1);
                }
                catch (SQLException ex) {
                    Logger.getLogger(GuiTien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else {
                JOptionPane.showMessageDialog(null,"Mã xác nhận chưa đúng", "Thông báo",1);
                String code= String.valueOf(random());
                txtRdcode.setText(code);
                txtCode.setText("");
            }
        }  
    }//GEN-LAST:event_btnGuiActionPerformed
  
    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int n = JOptionPane.showConfirmDialog(null,"Bạn có chắc bạn muốn thoát khỏi?", "Cảnh báo",JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION)
             ATMSystem.showPanel(new Wellcom());
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
            String code= String.valueOf(random());
            txtRdcode.setText(code);
    }//GEN-LAST:event_btnRefreshActionPerformed
    private int rand(int min,int max){
        try {
                Random rn = new Random();
                int range = max - min + 1;
                int randomNum = min + rn.nextInt(range);
                return randomNum;
            } catch (Exception e) {
                e.printStackTrace();
                return -1;
            }
     }
    private int random(){
          int rand = rand(1000,9000);
          return rand;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGui;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtRdcode;
    private javax.swing.JTextField txtSotien;
    // End of variables declaration//GEN-END:variables
}
