/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package atm;
import atm.Account;
import atm.Login;
import static atm.Account.Loginacount;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class RutTien extends javax.swing.JPanel {

    /** Creates new form RutTien */
    public RutTien() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn500 = new javax.swing.JButton();
        btn1000 = new javax.swing.JButton();
        btn2000 = new javax.swing.JButton();
        btn200 = new javax.swing.JButton();
        btn5000 = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnRut = new javax.swing.JButton();
        txtSotien = new javax.swing.JTextField();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Nhập số tiền cần rút");

        btn500.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn500.setText("500");
        btn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500ActionPerformed(evt);
            }
        });

        btn1000.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn1000.setText("1000");
        btn1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000ActionPerformed(evt);
            }
        });

        btn2000.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn2000.setText("2000");
        btn2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2000ActionPerformed(evt);
            }
        });

        btn200.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn200.setText("200");
        btn200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn200ActionPerformed(evt);
            }
        });

        btn5000.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn5000.setText("5000");
        btn5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5000ActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNew.setText("Nhập số khác");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnRut.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRut.setText("Rút tiền");
        btnRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn2000)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNew))
                    .addComponent(txtSotien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn200, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1000))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn5000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(33, 33, 33)
                .addComponent(btnRut)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRut)
                    .addComponent(txtSotien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn200)
                    .addComponent(btn500))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1000)
                    .addComponent(btn5000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2000)
                    .addComponent(btnNew))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void btn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500ActionPerformed
       String amuont="500";
       txtSotien.setText(amuont);   
    }//GEN-LAST:event_btn500ActionPerformed
    
    private void btn200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn200ActionPerformed
        String amuont="200";
        txtSotien.setText(amuont);
    }//GEN-LAST:event_btn200ActionPerformed

    private void btn1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000ActionPerformed
        String amuont="1000";
        txtSotien.setText(amuont);
    }//GEN-LAST:event_btn1000ActionPerformed

    private void btn5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5000ActionPerformed
     String amuont="5000";
       txtSotien.setText(amuont);
    }//GEN-LAST:event_btn5000ActionPerformed

    private void btn2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2000ActionPerformed
       String amuont="2000";
       txtSotien.setText(amuont);
    }//GEN-LAST:event_btn2000ActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
       txtSotien.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private int ktrAmount(String ktr){
        int kq=0;
        try 
        { 
            String regex = "^\\d+$"; 
            if(ktr.matches(regex)) 
            { 
                kq=1;
            } 
            else 
            { 
                kq=0;
            } 
        } 
        catch(Exception ex) 
        { 
            throw ex; 
        } 
        return kq;
    }
    private double sotien(){
        double tien,tienrut=0;
        String sotien=txtSotien.getText();
        if(ktrAmount(sotien)!=0){
            tien=Double.parseDouble(sotien);
            try {
                Account acc= new Account(ATMSystem.account);
                if(tien >= acc.getBalance() || tien <10 ){
                    tienrut = 0;
                }
                else tienrut=tien;
            } catch (SQLException ex) {
                Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else tienrut=0;
        return tienrut;
    }
    private void btnRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutActionPerformed
            String tien=txtSotien.getText();
            if(sotien()==0 || tien==null){
                JOptionPane.showMessageDialog(null,"Số tiền không hợp lệ", "Thông báo",1);
            }
            else{
                Deal dl=new Deal();
                try {
                    int rs = dl.Withdrawal(ATMSystem.account, "Rút tiền", "Thành công", sotien());
                    if(rs==0){
                        JOptionPane.showMessageDialog(null,"Rút tiền thành công", "Thông báo",1);
                        txtSotien.setText("");
                        int n = JOptionPane.showConfirmDialog(null,"Tiếp tục thực hiện các giao dịch ?", "Cảnh báo",JOptionPane.YES_NO_OPTION);
                        if(n == JOptionPane.YES_OPTION)
                               ATMSystem.showPanel(new Wellcom());
                        else if(n==JOptionPane.NO_OPTION){
                                   ATMSystem.account=0;
                                   JOptionPane.showMessageDialog(null, "Bạn đã đăng xuất");
                                   ATMSystem.showPanel(new Login());   
                               }
                    }
                    else JOptionPane.showMessageDialog(null,"Rút tiền không thành công", "Thông báo",1);
                }catch (SQLException ex) {
                    Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }    
       
    }//GEN-LAST:event_btnRutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1000;
    private javax.swing.JButton btn200;
    private javax.swing.JButton btn2000;
    private javax.swing.JButton btn500;
    private javax.swing.JButton btn5000;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSotien;
    // End of variables declaration//GEN-END:variables

}
